version: "3.7"
services:
  db:
    build:
      context: ./db
    image: db
    env_file: .env
    container_name: db_container
    working_dir: /db/pgdata
    volumes:
      - db-volume/:/db/pgdata
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - net
  app:
    build:
      context: ./
    image: server
    container_name: server_container
    env_file: .env
    ports:
      - "4000:4000"
    working_dir: /app
    volumes:
      - app-volume/:/app/logs
    restart: always
    links:
      - db
    networks:
      - net
volumes:
  app-volume:
  db-volume:
networks:
  net:
    driver: bridge
    name: net