version: "3.7"
services:
  postgres:
    image: postgres:14.1-alpine
    env_file: .env
    container_name: db_container
    volumes:
      - postgres_db:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_HOST_AUTH_METHOD: trust # Insecure connection, only for local
    networks:
      - net
  app:
    build:
      context: ./
    image: server:16.13-alpine
    container_name: server_container
    env_file: .env
    ports:
      - "${PORT}:${CONTAINER_PORT}"
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./src/:/app/src
      - app:/app/logs
    restart: always
    links:
      - postgres
    networks:
      - net
volumes:
  postgres_db:
  app:
networks:
  net:
    driver: bridge
    name: net